<?php
$Nama ="Al Vitto D Jibril";
$Kelas = "XI RPL B";
$NIS ="22131";
$Alamat ="Jl Silikat no 5";
$NO ="0813-5751-8380";
$TTL  ="Malang,-2005";
$Kelamin = "laki laki";
$Umur ="16";

   echo "<center><table wiidth = 420 height = 400 border = 9 border-radius = 3px >
   <tr>
   <td><center>
   <table cellspsasing =9>
   <h3 align= 'center'><b>Biodata siswa</h3>
   <tr>
     <td> nama </td>
     <td> :  </td>
     <td> $Nama </td>
     </tr>
     <tr>
       <td> Kelas </td>
       <td> : </td>
       <td> $Kelas </td>
    </tr>
    <tr>
       <td>Nis</td>
       <td>  : </td>
       <td> $Alamat </td>
    </tr>
    <tr>
      <td>NO</td>
      <td>  : </td>
      <td> $NO </td>
    </tr>
    <tr>
      <td>TTL</td>
      <td>  : </td> 
      <td> $TTL </td>
    </tr>
    <tr>
     <td> Kelamin </td>
     <td> :  </td>
     <td> $Kelamin</td>
     </tr>
     <tr>
     <tr>
     <td>Umur </td>
     <td> :  </td>
     <td> $Umur </td>
     </tr>
     <tr>
   </table>"
   ?>
